homeassistant:
  # Name of the location where Home Assistant is running
  name: Daheim
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include_dir_merge_named customize


updater:
config:
http:
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:
  ignore:
  enable:
    - homekit

conversation:
history:
logbook:
map:

sun:
cloud:
frontend: !include ./config/frontend.yaml
group: !include config/group.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include config/sensors.yaml
media_player: !include config/media_players.yaml
switch: !include config/switches.yaml
zone: !include config/zones.yaml
device_tracker: !include config/device_tracker.yaml
light: !include config/lights.yaml
#variable: !include config/variable.yaml

ios:
mqtt:
ifttt:
  key: !secret ifttt_key
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 3600
homekit:
  filter:
    include_domains:
      - climate
      - light
      - device_tracker
hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: true
proximity:
  home:
    ignored_zones:
      - Uni
    devices:
      - device_tracker.chris
    tolerance: 50
    unit_of_measurement: mi
