#
# Tracking with: OwnTracks/HA app,
# on hold to simplify - Bluetooth, TP-Link
#
- platform: owntracks
  max_gps_accuracy: 200

- platform: ping
  hosts:
    macbookprochris: !secret macbookprochris_ip
    #laserprinter: 192.168.0.8

#- platform: tplink
#  host: 192.168.0.1
#  username: !secret router_user
#  password: !secret router_pass
#  track_new_devices: false
#  consider_home: 300
