default_view:
  view: yes
  icon: mdi:home
  name: Hidden Ridge
  entities:
    - group.weather
    - group.media_player
    - group.living_room
    - group.devices
lights:
  view: yes
  icon: mdi:lightbulb
  name: Lights
  entities:
    - group.living_room_lights
media:
  view: yes
  icon: mdi:cast
  name: Media Players
  entities:
    - media_player.livingroom_assistant
    - media_player.kitchen_assistant
    - media_player.bedroom_assistant
    - media_player.livingroom_tv
    - media_player.livingroom_speaker
    - media_player.party_mode
    - media_player.all_speakers
    - media_player.dining_room_speaker
    - media_player.bedroom_speaker
    - media_player.livingroom_directv
    - media_player.mancave_tv
    - media_player.mancave_directv
    - media_player.guestroom_tv
    - media_player.rasplex
    - media_player.all_assistants
    - media_player.garage_speaker
    - media_player.bathroom_assistant
    - media_player.master_suite
    - media_player.house_party_protocol

settings:
  view: yes
  icon: mdi:settings
  name: Settings
  entities:
    - updater.updater
    - group.override
    - group.system_monitor
    - group.devices
    - group.cast_devices
    - camera.downstairs_front_door
    - camera.downstairs_yard
    - camera.upstairs_nursery

chris_iphone:
  - device_tracker.tristans_phone_wifi
  - device_tracker.tristans_phone_bt

weather:
  - sun.sun
  - sensor.dark_sky_temperature
  - sensor.dark_sky_daily_high_temperature
  - sensor.dark_sky_daily_low_temperature
  - sensor.dark_sky_summary
  - sensor.dark_sky_precip_probability
  - sensor.dark_sky_precip_intensity
override:
  control: hidden
  entities:
    - updater.updater
    - input_boolean.disable_away_mode
    - input_boolean.disable_alarm
    - switch.vacation_mode
    - group.simulate_presence
    - input_boolean.disable_all_automations
devices:
  - sensor.huebridge
  - sensor.myq
cast_devices:
  - sensor.google_home_livingroom
  - sensor.google_home_mini_kitchen
  - sensor.google_home_mini_bedroom
  - sensor.google_home_mini_bathroom
  - sensor.chromecast_audio_dining_room
system_monitor:
  - sensor.cpu_temperature
  - sensor.cpu
  - sensor.load_5m
  - sensor.disk
  - sensor.ram
